Refactor asset id and balance
Manta-Network/manta-crypto pull request #14
Opened 2021-07-05 04:36 UTC by stechu

This is part of manta wide refactor:
1. change Asset_id to `u32`, this is consistent with `pallet-asset`, as well as BIP-32 defined wallet standard
2. change Value/Balance to `u128`, most Polkadot asset will be fine (except very few uses u256)

In `manta-crypto`, the major change is the ECIES part, now the plain text before encryption would be:

<4 bytes asset id> || <16 bytes vlue>  = 20 bytes

Now, ECIES's symmetric encryption switched to AES-GCM, as a result, the cipher text is 36 bytes now:

<20 bytes ciphertext> || <16 bytes tag> = 40 bytes

2021-07-05 10:49 UTC, zhenfeizhang requested changes

2021-07-05 10:49 UTC, zhenfeizhang commented on Cargo.toml
> +aes-gcm = { version = "0.9.2"}
disable default?

2021-07-05 10:49 UTC, zhenfeizhang commented on src/ecies.rs
> +		let nonce = Nonce::from_slice(b"manta rocks!");
Is this `nonce` the IV?
if so `IV` needs to be 12 bytes and non-repeat...
See
https://crypto.stackexchange.com/questions/26783/ciphertext-and-tag-size-and-iv-transmission-with-aes-in-gcm-mode

2021-07-05 14:42 UTC, stechu commented on src/ecies.rs
> +		let nonce = Nonce::from_slice(b"manta rocks!");
Yes, non-repeat for the same encryption key. Here we are using a different key each time, so it might be fine?  We need to know the nonce deterministically when decrypt.

2021-07-05 14:48 UTC, stechu commented on Cargo.toml
> +aes-gcm = { version = "0.9.2"}
disable default will cause error when calling `encrypt` and `decrypt`. I might get around of that by using `encrypt_in_place` and `decrypt_in_place`.

2021-07-07 16:37 UTC, stechu commented on src/ecies.rs
> +		let nonce = Nonce::from_slice(b"manta rocks!");
@zhenfeizhang  https://github.com/zcash/zcash/blob/1249659a3bf63aa98743be1035da3d96af494414/src/zcash/NoteEncryption.cpp#L130
ZCash uses deterministic nonce for ECIES as well. FYI.

2021-07-08 05:22 UTC, Kevingislason approved these changes

2021-07-08 05:22 UTC, Kevingislason commented on src/ecies.rs
> +	type Ciphertext = [u8; 68];
I have half a mint to suggest making ciphertext a struct, would make all this code more readable:

```
pub struct EciesCiphertext {
    encryptedMessage: [u8;  36]
    ephemeralPublicKey: [u8;  36]
}
```

But this might be throwaway code if we switch to a different encryption scheme later. If you think this refactor will take more than a few minutes, probably best to ignore, and revist later.

2021-07-08 14:55 UTC, stechu commented on src/ecies.rs
> +	type Ciphertext = [u8; 68];
i agree. would do that later.

2021-07-08 18:23 UTC, gabcbrown approved these changes

2021-07-09 13:08 UTC, merged