Storage Refactor
Manta-Network/manta-crypto pull request #26
Opened 2021-09-07 00:08 UTC by stechu

This is part of the PR to adapt to new `pallet-manta-pay` storage design.

2021-09-19 16:43 UTC, bhgomes commented on src/incremental_merkle_tree/mod.rs
> +	) -> Result<Self, ArkError> {
Can we return `Self` here instead? There is no error condition.

2021-09-19 16:43 UTC, bhgomes commented on src/incremental_merkle_tree/mod.rs
> +		IncrementalMerkleTree::<P>::next_path_without_tree(
nit: You can use `Self::next_path_without_tree` here instead.

2021-09-19 16:50 UTC, bhgomes commented on src/incremental_merkle_tree/mod.rs
> +}
Can you return references here instead? The caller should decide whether they want to clone or not.

2021-09-19 16:53 UTC, bhgomes commented on src/incremental_merkle_tree/mod.rs
> +		new_leaf_digest: P::LeafDigest,
All of the non-copy types here can be passed by reference:

```rust
pub fn next_path_without_tree(
    two_to_one_hash_param: &TwoToOneParam<P>,
    tree_height: usize,
    current_index: usize,
    empty: bool,
    current_leaf: &P::LeafDigest,
    current_path: &Path<P>,
    new_leaf_digest: &P::LeafDigest,
) -> Result<(Path<P>, P::InnerDigest), ArkError>
{
    ... 
}
```

2021-09-19 16:54 UTC, bhgomes commented on src/incremental_merkle_tree/mod.rs
> +		};
Can be replaced by `let current_index = self.current_index().unwrap_or(0);`.

2021-09-19 16:58 UTC, bhgomes commented on src/merkle_tree.rs
> +		entry: Self::Leaf,
Like above, the non-copy types should be passed by reference.

2021-09-19 16:59 UTC, bhgomes commented on src/param.rs
> +/// Merkle Tree Membership Variable (see [`LedgerMembership`])
`AccountMembership` was changed to `LedgerPath` not `LedgerMembership`.

2021-09-19 17:00 UTC, bhgomes commented on src/tests.rs
> +	let re = LedgerMerkleTree::blank(&leaf_param, &two_to_one_param, constants::MERKLE_TREE_DEPTH);
This never fails gracefully. We should test the panic condition if anything.

2021-09-19 17:01 UTC, bhgomes commented on src/param.rs
>  // TODO[check]: can we change this name to be consistent with other variable names?
nit: remove the `TODO[check]` comment.

2021-09-19 17:06 UTC, bhgomes requested changes
See comments above. Otherwise, LGTM.

2021-09-19 22:42 UTC, stechu commented on src/incremental_merkle_tree/mod.rs
> +	) -> Result<Self, ArkError> {
the `assert!` is the error condition?

2021-09-19 22:46 UTC, bhgomes commented on src/incremental_merkle_tree/mod.rs
> +	) -> Result<Self, ArkError> {
It's a panic not an error. It doesn't return `Result::Err` it crashes.

2021-09-21 21:25 UTC, bhgomes commented on Cargo.toml
> +manta-error = { path= "../manta-error", default-features = false }
This has to be changed back to the `git` dependency.

2021-09-21 21:27 UTC, bhgomes requested changes
See the `Cargo.toml`. Otherwise LGTM.

2021-09-22 04:05 UTC, Kevingislason reviewed
LGTM

2021-09-22 04:28 UTC, bhgomes commented on src/constants.rs
> +}
This is a general problem with the arkworks ecosystem. 99% of their functions that have fallible interfaces don't actually have error paths in them. All of this will be replaced soon, so I don't care either way if u want to have these functions have error paths or not.

2021-09-22 04:29 UTC, bhgomes commented on src/incremental_merkle_tree/mod.rs
> +		assert!(self.next_available() != None, "index out of range");
This is just to match the way arkworks does things. When we use the merkle tree we will remove this.

2021-09-22 04:30 UTC, bhgomes commented on src/param.rs
>  	// TODO: on the arkworks development branch `CRH` was fixed to `TwoToOneCRH`, we'll need to fix
Yes. It can be removed.

2021-09-22 04:31 UTC, bhgomes commented on src/incremental_merkle_tree/tests/mod.rs
> +	#[test]
This is copied directly from arkworks.

2021-09-22 15:28 UTC, merged